"""empty message

Revision ID: 6e9e297805ff
Revises: 41e87e24381c
Create Date: 2016-05-04 16:04:01.555804

"""

# revision identifiers, used by Alembic.
revision = '6e9e297805ff'
down_revision = '41e87e24381c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('mobile', sa.String(), nullable=False),
    sa.Column('gender', sa.CHAR(), nullable=True),
    sa.Column('profile_pic', sa.String(), nullable=True),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_table('user')
    op.drop_constraint(u'shopping_cart_user_id_fkey', 'shopping_cart', type_='foreignkey')
    op.create_foreign_key(None, 'shopping_cart', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shopping_cart', type_='foreignkey')
    op.create_foreign_key(u'shopping_cart_user_id_fkey', 'shopping_cart', 'user', ['user_id'], ['id'])
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mobile', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.CHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('DOB', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('profile_pic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('authenticated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'user_pkey')
    )
    op.drop_table('users')
    ### end Alembic commands ###
