"""empty message

Revision ID: 2db9e52cb3df
Revises: d6db9916c9bf
Create Date: 2016-05-12 20:47:19.751873

"""

# revision identifiers, used by Alembic.
revision = '2db9e52cb3df'
down_revision = 'd6db9916c9bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
