"""empty message

Revision ID: 36b4ca039cc5
Revises: 6a9d5e1927c7
Create Date: 2016-05-04 22:51:23.618015

"""

# revision identifiers, used by Alembic.
revision = '36b4ca039cc5'
down_revision = '6a9d5e1927c7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('images', postgresql.JSON(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'images')
    ### end Alembic commands ###
