"""empty message

Revision ID: 38a48b622ebf
Revises: 516b8770dea4
Create Date: 2016-11-09 20:53:35.438899

"""

# revision identifiers, used by Alembic.
revision = '38a48b622ebf'
down_revision = '516b8770dea4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('main_image', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'main_image')
    ### end Alembic commands ###
