"""empty message

Revision ID: 3e02f445dcff
Revises: 2db9e52cb3df
Create Date: 2016-05-12 20:49:27.936311

"""

# revision identifiers, used by Alembic.
revision = '3e02f445dcff'
down_revision = '2db9e52cb3df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'DOB')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('DOB', sa.DATE(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
