"""empty message

Revision ID: 4a738d4b146d
Revises: 3e02f445dcff
Create Date: 2016-05-12 20:49:49.160141

"""

# revision identifiers, used by Alembic.
revision = '4a738d4b146d'
down_revision = '3e02f445dcff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('DOB', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'DOB')
    ### end Alembic commands ###
