"""empty message

Revision ID: 4e65c50a8f43
Revises: 606f1c697d22
Create Date: 2016-08-18 13:56:26.337185

"""

# revision identifiers, used by Alembic.
revision = '4e65c50a8f43'
down_revision = '606f1c697d22'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('latitude', postgresql.DOUBLE_PRECISION(), nullable=True))
    op.add_column('shop', sa.Column('longitude', postgresql.DOUBLE_PRECISION(), nullable=True))
    op.drop_column('shop', 'lat')
    op.drop_column('shop', 'lon')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('lon', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('shop', sa.Column('lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('shop', 'longitude')
    op.drop_column('shop', 'latitude')
    ### end Alembic commands ###
