"""empty message

Revision ID: 516b8770dea4
Revises: None
Create Date: 2016-11-09 20:01:16.599122

"""

# revision identifiers, used by Alembic.
revision = '516b8770dea4'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('date_add', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('date_upd', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('date_add', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('date_upd', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('passwd', sa.String(), nullable=False),
    sa.Column('profile_pic', sa.String(), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.CHAR(), nullable=True),
    sa.Column('fav_lan', sa.Integer(), nullable=True),
    sa.Column('longitude', postgresql.DOUBLE_PRECISION(), nullable=True),
    sa.Column('latitude', postgresql.DOUBLE_PRECISION(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('fb_token', sa.String(), nullable=True),
    sa.Column('fb_id', sa.String(), nullable=True),
    sa.Column('device_token', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('date_add', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('date_upd', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('floor_num', sa.Integer(), nullable=True),
    sa.Column('building_num', sa.Integer(), nullable=True),
    sa.Column('street_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('date_add', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('date_upd', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('passwd', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('date_add', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('date_upd', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['agents_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_parent', sa.Integer(), nullable=True),
    sa.Column('level_depth', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('id_image', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('date_add', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('date_upd', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_image'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('date_add', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('date_upd', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_image', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('date_add', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('date_upd', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_image'], ['images.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_current_state', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_address', sa.Integer(), nullable=True),
    sa.Column('id_phone', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('date_add', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('date_upd', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_address'], ['address.id'], ),
    sa.ForeignKeyConstraint(['id_current_state'], ['order_status.id'], ),
    sa.ForeignKeyConstraint(['id_phone'], ['phone.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id_supplier', sa.Integer(), nullable=True),
    sa.Column('id_manufacturer', sa.Integer(), nullable=True),
    sa.Column('id_category', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.String(length=8), nullable=True),
    sa.Column('on_sale', sa.Boolean(), nullable=True),
    sa.Column('wholesale_price', sa.DECIMAL(), nullable=True),
    sa.Column('reduction_price', sa.DECIMAL(), nullable=True),
    sa.Column('reduction_percent', sa.FLOAT(), nullable=True),
    sa.Column('reduction_from', sa.DateTime(), nullable=True),
    sa.Column('reduction_to', sa.DateTime(), nullable=True),
    sa.Column('out_of_stock', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('date_add', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('date_upd', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_category'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_order', sa.Integer(), nullable=True),
    sa.Column('id_product', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('date_add', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('date_upd', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_order'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['id_product'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_order', sa.Integer(), nullable=True),
    sa.Column('id_agent', sa.Integer(), nullable=True),
    sa.Column('id_status', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('date_add', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('date_upd', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_agent'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['id_order'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['id_status'], ['order_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=True),
    sa.Column('attr_name', sa.String(), nullable=True),
    sa.Column('attr_description', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('date_add', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('date_upd', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_product'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=True),
    sa.Column('id_image', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('date_add', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('date_upd', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_image'], ['images.id'], ),
    sa.ForeignKeyConstraint(['id_product'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('use_recently_viewed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_product', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('date_add', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('date_upd', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_product'], ['products.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('use_recently_viewed')
    op.drop_table('product_images')
    op.drop_table('product_attribute')
    op.drop_table('order_process')
    op.drop_table('cart')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('user_images')
    op.drop_table('phone')
    op.drop_table('category')
    op.drop_table('agents')
    op.drop_table('address')
    op.drop_table('users')
    op.drop_table('order_status')
    op.drop_table('images')
    op.drop_table('agents_role')
    ### end Alembic commands ###
