"""empty message

Revision ID: 606f1c697d22
Revises: 0897a5267f59
Create Date: 2016-08-18 13:55:37.421012

"""

# revision identifiers, used by Alembic.
revision = '606f1c697d22'
down_revision = '0897a5267f59'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('lat', postgresql.DOUBLE_PRECISION(), nullable=True))
    op.add_column('shop', sa.Column('lon', postgresql.DOUBLE_PRECISION(), nullable=True))
    op.drop_column('shop', 'latitude')
    op.drop_column('shop', 'longitude')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('longitude', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shop', sa.Column('latitude', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('shop', 'lon')
    op.drop_column('shop', 'lat')
    ### end Alembic commands ###
