"""empty message

Revision ID: 6a9d5e1927c7
Revises: 894dade737dd
Create Date: 2016-05-04 22:37:43.526349

"""

# revision identifiers, used by Alembic.
revision = '6a9d5e1927c7'
down_revision = '894dade737dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('short_description', sa.String(length=250), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'short_description')
    ### end Alembic commands ###
