"""empty message

Revision ID: 6aa9929c4055
Revises: 4a738d4b146d
Create Date: 2016-05-12 20:49:59.600798

"""

# revision identifiers, used by Alembic.
revision = '6aa9929c4055'
down_revision = '4a738d4b146d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.CHAR(length=1), autoincrement=False, nullable=True))
    ### end Alembic commands ###
