"""empty message

Revision ID: 79d2ca077af3
Revises: a08bd29ce7e5
Create Date: 2016-05-04 13:38:31.783118

"""

# revision identifiers, used by Alembic.
revision = '79d2ca077af3'
down_revision = 'a08bd29ce7e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('hasSub', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('parentCat', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parentCat'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_category')
    op.drop_table('category')
    ### end Alembic commands ###
