"""empty message

Revision ID: 83ee39f6c684
Revises: 38a48b622ebf
Create Date: 2016-11-16 23:45:20.697766

"""

# revision identifiers, used by Alembic.
revision = '83ee39f6c684'
down_revision = '38a48b622ebf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'price')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    ### end Alembic commands ###
