"""empty message

Revision ID: 88671494a6e3
Revises: 9d53ee853b44
Create Date: 2016-05-04 16:06:22.883180

"""

# revision identifiers, used by Alembic.
revision = '88671494a6e3'
down_revision = '9d53ee853b44'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('DOB', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'DOB')
    ### end Alembic commands ###
