"""empty message

Revision ID: 894dade737dd
Revises: c3246a5a6074
Create Date: 2016-05-04 20:30:47.563364

"""

# revision identifiers, used by Alembic.
revision = '894dade737dd'
down_revision = 'c3246a5a6074'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('created', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True))
    op.add_column('items', sa.Column('updated', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True))
    op.drop_column('items', 'timestamp')
    op.add_column('orders', sa.Column('created', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True))
    op.add_column('orders', sa.Column('updated', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True))
    op.drop_column('orders', 'timestamp')
    op.add_column('shop', sa.Column('created', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True))
    op.add_column('shop', sa.Column('updated', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True))
    op.drop_column('shop', 'timestamp')
    op.add_column('shopping_cart', sa.Column('created', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True))
    op.add_column('shopping_cart', sa.Column('updated', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True))
    op.drop_column('shopping_cart', 'timestamp')
    op.add_column('users', sa.Column('created', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True))
    op.add_column('users', sa.Column('updated', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True))
    op.drop_column('users', 'timestamp')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'updated')
    op.drop_column('users', 'created')
    op.add_column('shopping_cart', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('shopping_cart', 'updated')
    op.drop_column('shopping_cart', 'created')
    op.add_column('shop', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('shop', 'updated')
    op.drop_column('shop', 'created')
    op.add_column('orders', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'updated')
    op.drop_column('orders', 'created')
    op.add_column('items', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('items', 'updated')
    op.drop_column('items', 'created')
    ### end Alembic commands ###
