"""empty message

Revision ID: a08bd29ce7e5
Revises: c3958357d911
Create Date: 2016-05-04 13:29:07.902959

"""

# revision identifiers, used by Alembic.
revision = 'a08bd29ce7e5'
down_revision = 'c3958357d911'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('owner_email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('gender', sa.CHAR(), nullable=True),
    sa.Column('shop_name', sa.String(length=250), nullable=True),
    sa.Column('shop_profile_pic', sa.String(length=200), nullable=True),
    sa.Column('shop_cover_pic', sa.String(length=200), nullable=True),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('shop_address', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop')
    ### end Alembic commands ###
