"""empty message

Revision ID: a98f785fd92c
Revises: ec7cd84a4e4c
Create Date: 2016-05-12 20:18:54.408045

"""

# revision identifiers, used by Alembic.
revision = 'a98f785fd92c'
down_revision = 'ec7cd84a4e4c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'mobile',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'mobile',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###
