"""empty message

Revision ID: c3246a5a6074
Revises: 8980a79fec72
Create Date: 2016-05-04 20:27:30.655505

"""

# revision identifiers, used by Alembic.
revision = 'c3246a5a6074'
down_revision = '8980a79fec72'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('shipping_address', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'items', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column(u'shop', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column(u'shopping_cart', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column(u'users', sa.Column('timestamp', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', 'timestamp')
    op.drop_column(u'shopping_cart', 'timestamp')
    op.drop_column(u'shop', 'timestamp')
    op.drop_column(u'items', 'timestamp')
    op.drop_table('orders')
    ### end Alembic commands ###
