"""empty message

Revision ID: c5216684d593
Revises: f5f5a818f3dd
Create Date: 2016-11-22 13:18:06.313476

"""

# revision identifiers, used by Alembic.
revision = 'c5216684d593'
down_revision = 'f5f5a818f3dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('id_user', sa.Integer(), nullable=True))
    op.drop_constraint(u'cart_id_order_fkey', 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'users', ['id_user'], ['id'])
    op.drop_column('cart', 'id_order')
    op.add_column('orders', sa.Column('id_cart', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'cart', ['id_cart'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'id_cart')
    op.add_column('cart', sa.Column('id_order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key(u'cart_id_order_fkey', 'cart', 'orders', ['id_order'], ['id'])
    op.drop_column('cart', 'id_user')
    ### end Alembic commands ###
