"""empty message

Revision ID: c6a91921679b
Revises: 36b4ca039cc5
Create Date: 2016-05-08 19:20:56.220811

"""

# revision identifiers, used by Alembic.
revision = 'c6a91921679b'
down_revision = '36b4ca039cc5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'status')
    ### end Alembic commands ###
