"""empty message

Revision ID: d6db9916c9bf
Revises: a98f785fd92c
Create Date: 2016-05-12 20:43:37.642116

"""

# revision identifiers, used by Alembic.
revision = 'd6db9916c9bf'
down_revision = 'a98f785fd92c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token')
    ### end Alembic commands ###
