"""empty message

Revision ID: d7f9bf213f7b
Revises: 6e9e297805ff
Create Date: 2016-05-04 16:04:55.297688

"""

# revision identifiers, used by Alembic.
revision = 'd7f9bf213f7b'
down_revision = '6e9e297805ff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.add_column('users', sa.Column('DOB', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'DOB')
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mobile', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.CHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('DOB', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('profile_pic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('authenticated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'user_pkey')
    )
    ### end Alembic commands ###
