"""empty message

Revision ID: ec7cd84a4e4c
Revises: c6a91921679b
Create Date: 2016-05-09 13:36:41.586049

"""

# revision identifiers, used by Alembic.
revision = 'ec7cd84a4e4c'
down_revision = 'c6a91921679b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('device_token', sa.String(), nullable=True))
    op.add_column('shop', sa.Column('fb_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('device_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('fb_token', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fb_token')
    op.drop_column('users', 'device_token')
    op.drop_column('shop', 'fb_token')
    op.drop_column('shop', 'device_token')
    ### end Alembic commands ###
